version: '3.5'

services:
    flask:
        container_name: attach_build
        image: attach_build
        restart: always
        ports:
            - '5001:5001'
        volumes:
            - ./app:/app
        networks:
            - backend
        depends_on:
            - mysql

    mysql:
        container_name: mysql
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: warehouse
            MYSQL_ROOT_PASSWORD: 123qwezxc
        ports:
            - '3308:3306'
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - backend

networks:
    backend:

volumes:
    app:
    database: